# A docker-compose for redis and flask app 

version: '3.7'

services:
  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - data:/data

  flask:
    build: .
    container_name: flask
    restart: always
    ports:
      - 8192:8192

  worker:
    build: .
    hostname: worker
    entrypoint: celery
    container_name: worker
    restart: always
    command: -A app.celery_tasks worker --loglevel=info
    links:
      - redis
    depends_on:
      - redis
    volumes:
      - ansible:/ansible
    environment:
      - AMIGA_SSH_KEY

volumes:
  data:
  ansible: